[workspace]
members = [
    "crates/j-agent",
    "crates/j-cli",
    "crates/j-tui",
    "crates/j-md",
    "apps/desktop/src-tauri",
]
resolver = "2"

[workspace.package]
version = "12.10.81"
edition = "2024"
rust-version = "1.93.1"
license = "MIT"
repository = "https://github.com/LingoJack/jcli"
